kind: "Template"
apiVersion: "v1"
metadata:
  name: "test-springboot-jenkins-openshift"
objects:
  - kind: "Service" 
    apiVersion: "v1"
    metadata:
      app: "test-springboot-jenkins-openshift"
      name: "test-springboot-jenkins-openshift"
    spec:
      ports:
        - name: 8084-tcp
          port: 8084
          protocol: TCP
          targetPort: 8084
      selector:
        name: "test-springboot-jenkins-openshift"
        deploymentconfig: "test-springboot-jenkins-openshift"