kind: "Template"
apiVersion: "v1"
metadata:
  name: "test-springboot-jenkins-openshift"
objects:
  - kind: "Service" 
    apiVersion: "v1"
    metadata:
      app: "test-springboot-jenkins-openshift"
      name: "test-springboot-jenkins-openshift"
    spec:
      ports:
        - name: 8090-tcp
          port: 8090
          protocol: TCP
          targetPort: 8090
      selector:
        name: "test-springboot-jenkins-openshift"
        deploymentconfig: "test-springboot-jenkins-openshift"
  - kind: "Route" 
    apiVersion: "v1"
    metadata:
      app: "test-springboot-jenkins-openshift"
      name: "test-springboot-jenkins-openshift"
    spec:
      to:
        kind: Service
        name: "test-springboot-jenkins-openshift"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
       app: "test-springboot-jenkins-openshift"
       name: "test-springboot-jenkins-openshift"
    spec:
      replicas: 1
      selector:
        app: "test-springboot-jenkins-openshift"
        deploymentconfig: "test-springboot-jenkins-openshift"
      strategy:
        type: Recreate
      template:
       metadata:
            app: "test-springboot-jenkins-openshift"
            deploymentconfig: "test-springboot-jenkins-openshift"