kind: "Template"
apiVersion: "v1"
metadata:
  name: "test-springboot-jenkins-openshift"
objects:
 - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "test-springboot-jenkins-openshift"
      name: "test-springboot-jenkins-openshift"
    spec:
      ports:
        - name: 8090-tcp
          port: 8090
          protocol: TCP
          targetPort: 8090
      selector:
        app: "test-springboot-jenkins-openshift"
        deploymentconfig: "test-springboot-jenkins-openshift"
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: "test-springboot-jenkins-openshift"
      name: "test-springboot-jenkins-openshift"
    spec:
      to:
        kind: Service
        name: "test-springboot-jenkins-openshift"